//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDocuments
    {
        public int DocumentID { get; set; }
        public int UserId { get; set; }
        public string DocumentUrl { get; set; }
        public string UniqueGuid { get; set; }
        public string AddedBy { get; set; }
        public string Date { get; set; }
    }
}
