//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationPageAsp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdsOfRolesAndUsers
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Roles Roles1 { get; set; }
        public virtual UserDetails UserDetails { get; set; }
        public virtual UserDetails UserDetails1 { get; set; }
    }
}
