//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationPageAsp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes
    {
        public int NoteId { get; set; }
        public int UserId { get; set; }
        public string Note { get; set; }
        public Nullable<int> IsPrivate { get; set; }
    
        public virtual UserDetails UserDetails { get; set; }
    }
}
