//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelManagementsystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelTransaction
    {
        public int transactionId { get; set; }
        public string transactionDataTime { get; set; }
        public string transactionType { get; set; }
        public int airportId { get; set; }
        public Nullable<int> aircraftId { get; set; }
        public int quantity { get; set; }
        public Nullable<int> transactionIdParent { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airport Airport { get; set; }
    }
}
